name: 01-building-blocks.yaml
on:
 push:
jobs:
 echo-helo-world:
  runs-on:
   ubuntu-latest
  steps:
   - run: echo "Hello, World!"
 echo-goodbye:
  runs-on:
   ubuntu-latest
  steps:
   - name: Multi-line bash 
     run: | 
      echo "I am" 
      echo "failed" 
      echo "Failed."
   - run: echo "Hello, Goodbye"
