name: 01-building-blocks.yaml
on:
 push:
jobs:
 echo-helo-world:
  runs-on:
   ubuntu-latest
  steps:
   - run: echo "Hello, World!"
 echo-goodbye:
  runs-on:
   ubuntu-latest
  steps:
   - run: echo "Hello, Goodbye"
   
