name: 02 - Workflow Events

on:
  # Trigger the workflow on push events (to any branch)
  push:
    branches:
      - '*'
  # Trigger the workflow on pull request events (open, synchronize, or reopen)
  pull_request:
    branches:
      - '*'
  # Trigger the workflow on a schedule (daily at midnight UTC)
  schedule:
    - cron: '0 0 * * *'  # Run at midnight UTC every day
  # Trigger the workflow manually via the GitHub UI (workflow_dispatch)
  workflow_dispatch:

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Show the trigger
        run: |
          echo "Event name: ${{ github.event_name }}"
